### ISSUE TITLE
Seperate blacklist and whitelist to another repo and load them via network

### ISSUE THREAD

**Issue by Jerrywang959** [DAOBuidler/MetaShieldExtension#16]
Is that more agile?

**Comment by 0xbe1** [comment]
doesn't have to be in a separate repo, just hosting them as file should be good enough

**Comment by aboutmydreams** [comment]
Hello @Jerrywang959 , great to receive your issue, it doesn't seem to be much positive for the open source community to actively contribute in the new repository? And additional consideration needs to be given to network request delays and failures

**Comment by Jerrywang959** [comment]
For separation, I think the `backlist` and `whitelist` can be more open and shared with the community. For instance, [ACLSSR](https://github.com/ACL4SSR/ACL4SSR), [easylist](https://github.com/easylist/easylist).

For loading via the network, I recommend regular updates and caching. If just the list is updated, should every user update the extension? People who travel in web3 should have the ability to resolve network request delays and failures by themselves.

**Comment by creeep123** [comment]
> For separation, I think the `backlist` and `whitelist` can be more open and shared with the community. For instance, [ACLSSR](https://github.com/ACL4SSR/ACL4SSR), [easylist](https://github.com/easylist/easylist).
> 
> For loading via the network, I recommend regular updates and caching. If just the list is updated, should every user update the extension? People who travel in web3 should have the ability to resolve network request delays and failures by themselves.

Hello Jerry, this is exactly the problem we have considered before. In order to avoid frequent local updates of the black/white list, we adopt a solution that does not cache the black/white list in browser, but checks "black and white list or not" on the server side, and only returns the result.

**Comment by aboutmydreams** [comment]
User has not responded for a long time
